let properties: Array<any> = [
    {
        id: 1,
        name: "Jayathunga K.L",
        address: "116/F Welivita, Kaduwela",
        contact:"0712566198",
        city: "Kaduwela",
        district: "Colombo",
        type: "Carpenter",
        experience: "20 Years",
        picture: "https://media.istockphoto.com/vectors/service-icon-vector-male-person-worker-avatar-profile-with-gear-cog-vector-id900946328",
        thumbnail: "https://media.istockphoto.com/vectors/service-icon-vector-male-person-worker-avatar-profile-with-gear-cog-vector-id900946328",
        tags: "colonial"
    },
    {
        id: 2,
        name: "Kasun A.R.L",
        address: "116/F Welivita, Kaduwela",
        contact:"0712566198",
        city: "Kaduwela",
        district: "Colombo",
        type: "Tile",
        experience: "20 Years",
        picture: "https://media.istockphoto.com/vectors/service-icon-vector-male-person-worker-avatar-profile-with-gear-cog-vector-id900946328",
        thumbnail: "https://media.istockphoto.com/vectors/service-icon-vector-male-person-worker-avatar-profile-with-gear-cog-vector-id900946328",
        tags: "colonial"
    },
    {
        id: 3,
        name: "Samantha A.S.D",
        address: "116/F Kandana,Dehiwala",
        contact:"0712566198",
        city: "Dehiwala",
        district: "Colombo",
        type: "Plumber",
        experience: "10 Years",
        picture: "https://media.istockphoto.com/vectors/service-icon-vector-male-person-worker-avatar-profile-with-gear-cog-vector-id900946328",
        thumbnail: "https://media.istockphoto.com/vectors/service-icon-vector-male-person-worker-avatar-profile-with-gear-cog-vector-id900946328",
        tags: "colonial"
    },
    {
        id: 4,
        name: "Jayathunga K.L",
        address: "116/F Welivita, Kaduwela",
        contact:"0712566198",
        city: "Kaduwela",
        district: "Colombo",
        type: "Painter",
        experience: "20 Years",
        picture: "https://media.istockphoto.com/vectors/service-icon-vector-male-person-worker-avatar-profile-with-gear-cog-vector-id900946328",
        thumbnail: "https://media.istockphoto.com/vectors/service-icon-vector-male-person-worker-avatar-profile-with-gear-cog-vector-id900946328",
        tags: "colonial"
    },
    {
        id: 5,
        name: "Jayathunga K.L",
        address: "116/F Welivita, Kaduwela",
        contact:"0712566198",
        city: "Kaduwela",
        district: "Colombo",
        type: "Painter",
        experience: "20 Years",
        picture: "https://media.istockphoto.com/vectors/service-icon-vector-male-person-worker-avatar-profile-with-gear-cog-vector-id900946328",
        thumbnail: "https://media.istockphoto.com/vectors/service-icon-vector-male-person-worker-avatar-profile-with-gear-cog-vector-id900946328",
        tags: "colonial"
    },
    {
        id: 6,
        name: "Jayathunga K.L",
        address: "116/F Welivita, Kaduwela",
        contact:"0712566198",
        city: "Kaduwela",
        district: "Colombo",
        type: "Welding",
        experience: "20 Years",
        picture: "https://media.istockphoto.com/vectors/service-icon-vector-male-person-worker-avatar-profile-with-gear-cog-vector-id900946328",
        thumbnail: "https://media.istockphoto.com/vectors/service-icon-vector-male-person-worker-avatar-profile-with-gear-cog-vector-id900946328",
        tags: "colonial"
    },
    {
        id: 7,
        name: "Jayathunga K.L",
        address: "116/F Welivita, Kaduwela",
        contact:"0712566198",
        city: "Kaduwela",
        district: "Colombo",
        type: "Welding",
        experience: "20 Years",
        picture: "https://media.istockphoto.com/vectors/service-icon-vector-male-person-worker-avatar-profile-with-gear-cog-vector-id900946328",
        thumbnail: "https://media.istockphoto.com/vectors/service-icon-vector-male-person-worker-avatar-profile-with-gear-cog-vector-id900946328",
        tags: "colonial"
    },
    {
        id: 8,
        name: "Jayathunga K.L",
        address: "116/F Welivita, Kaduwela",
        contact:"0712566198",
        city: "Kaduwela",
        district: "Colombo",
        type: "Welding",
        experience: "20 Years",
        picture: "https://media.istockphoto.com/vectors/service-icon-vector-male-person-worker-avatar-profile-with-gear-cog-vector-id900946328",
        thumbnail: "https://media.istockphoto.com/vectors/service-icon-vector-male-person-worker-avatar-profile-with-gear-cog-vector-id900946328",
        tags: "colonial"
    },
    {
        id: 9,
        name: "Jayathunga K.L",
        address: "116/F Welivita, Kaduwela",
        contact:"0712566198",
        city: "Kaduwela",
        district: "Colombo",
        type: "Welding",
        experience: "20 Years",
        picture: "https://media.istockphoto.com/vectors/service-icon-vector-male-person-worker-avatar-profile-with-gear-cog-vector-id900946328",
        thumbnail: "https://media.istockphoto.com/vectors/service-icon-vector-male-person-worker-avatar-profile-with-gear-cog-vector-id900946328",
        tags: "colonial"
    },
    {
        id: 10,
        name: "Jayathunga K.L",
        address: "116/F Welivita, Kaduwela",
        contact:"0712566198",
        city: "Kaduwela",
        district: "Colombo",
        type: "Vehicle Repairs",
        experience: "20 Years",
        picture: "https://media.istockphoto.com/vectors/service-icon-vector-male-person-worker-avatar-profile-with-gear-cog-vector-id900946328",
        thumbnail: "https://media.istockphoto.com/vectors/service-icon-vector-male-person-worker-avatar-profile-with-gear-cog-vector-id900946328",
        tags: "colonial"
    }
];

export default properties;
